apiVersion: v1
kind: ConfigMap
metadata:
  name: bye-config
data:
  bye.py: |
    import logging
    import time

    def main():
        logging.info("Good bye!")
        print("Good bye!")
        time.sleep(1)

    if __name__ == '__main__':
        for i in range(10):
            main()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bye-deployment
spec:
  selector:
    matchLabels:
      app: bye
  replicas: 3
  template:
    metadata:
      labels:
        app: bye
    spec:
      containers:
      - name: bye
        image: python:3.9-slim-bullseye
        imagePullPolicy: Always
        command: ["python3", "bye.py"]
        volumeMounts:
        - name: bye-config
          mountPath: /bye.py
          subPath: bye.py
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: bye-config
        configMap:
          name: bye-config