apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  hello.py: |
    import logging
    import time

    def main():
        logging.info("Hello world!")
        print("Hello world!")
        time.sleep(1)

    if __name__ == '__main__':
        for i in range(10):
            main()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 5
  template:
    metadata:
      labels:
        app: hello
    spec:
      nodeSelector:
        node-type: worker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - knode01
      containers:
      - name: hello
        image: python:3.9-slim-bullseye
        imagePullPolicy: Always
        command: ["python3", "hello.py"]
        volumeMounts:
        - name: hello-config
          mountPath: /hello.py
          subPath: hello.py
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: hello-config
        configMap:
          name: hello-config