apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-configmap
data:
    sensor.py: |
      import RPi.GPIO as GPIO
      import time

      MOTION_PIN = 23

      GPIO.setmode(GPIO.BCM)
      GPIO.setup(MOTION_PIN, GPIO.IN)

      try:
          while True:
              motion_detected = GPIO.input(MOTION_PIN)
              if motion_detected:
                  print("Motion detected")
              else:
                  print("No motion")
              time.sleep(1)
      except KeyboardInterrupt:
          GPIO.cleanup()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-deployment
  labels:
    app: sensor
spec:
  selector:
    matchLabels:
      app: sensor
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
      - name: sensor
        image: python:3.9-slim-bullseye 
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "apt-get update && apt-get install -y sudo gcc && pip install RPi.GPIO && sudo python3 /sensor.py"]
        securityContext:
          privileged: true
          runAsUser: 0  
        volumeMounts:
        - name: sensor-configmap
          mountPath: /sensor.py
          subPath: sensor.py
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: sensor-configmap
        configMap:
          name: sensor-configmap
